package de.swiesend.secretservice.functional.interfaces;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.function.Function;

public interface CollectionInterface extends AutoCloseable {

    /**
     * Clear the collection password.
     *
     * @return true, if password could be cleared else false.
     */
    boolean clear();

    /**
     * Create an item in the collection.
     *
     * @param label  The label is a description. It is not a unique identifier.
     * @param secret The secret to be stored. One can encrypt the secret in beforehand,
     *               to avoid unwanted access from malicious applications.
     * @return item path, which is a unique reference generated by the provider
     */
    Optional<String> createItem(String label, CharSequence secret);

    /**
     * Create an item in the collection.
     *
     * @param label      The label is a description. It is not a unique identifier.
     * @param secret     The secret to be stored. One can encrypt the secret in beforehand,
     *                   to avoid unwanted access from malicious applications.
     * @param attributes Attributes are provided as a mapping of custom keys and values.
     *                   Applications often identify their secrets using the key `application`
     *                   and their application name as value and providing a unique identifier
     *                   for a specific secret in order to find it by its attributes instead
     *                   of the generated item path.
     *                   <p>
     *                   e.g.:
     *                   <code>
     *                   {
     *                   "application": "APPLICATION_NAME",
     *                   "uuid": "f773dd93-4869-4897-be9d-c53f5b43f904"
     *                   }
     *                   </code>
     * @return item path, which is a unique reference generated by the provider
     */
    Optional<String> createItem(String label, CharSequence secret, Map<String, String> attributes);

    boolean delete();

    boolean deleteItem(String objectPath);

    boolean deleteItems(List<String> objectPaths);

    Optional<Map<String, String>> getAttributes(String objectPath);

    Optional<List<String>> getItems(Map<String, String> attributes);

    Optional<String> getItemLabel(String objectPath);

    boolean setItemLabel(String objectPath, String label);

    boolean setLabel(String label);

    Optional<String> getLabel();

    Optional<String> getId();

    /**
     * Retrieve a decrypted secret by its object path.
     *
     * <p><b>Security note:</b> The caller is responsible for clearing the returned {@code char[]}
     * after use (e.g., {@code Arrays.fill(chars, '\0')}) to prevent sensitive material from
     * lingering in heap memory. Prefer {@link #withSecret(String, Function)} which handles
     * cleanup automatically.</p>
     *
     * @param objectPath the D-Bus object path of the item
     * @return the decrypted secret as a char array, or empty if the item does not exist or is locked
     */
    Optional<char[]> getSecret(String objectPath);

    /**
     * Access a decrypted secret within a callback, guaranteeing the secret bytes are cleared
     * from memory after the callback returns (or throws).
     *
     * <p>This is the recommended way to access secrets. The library decrypts the secret,
     * passes the {@code char[]} to the callback, and zeroes the array in a {@code finally}
     * block -- the caller never needs to manage cleanup.</p>
     *
     * <p>Example usage:</p>
     * <pre>{@code
     * Optional<Boolean> authenticated = collection.withSecret(itemPath, secret -> {
     *     return checkPassword(secret);
     * });
     * }</pre>
     *
     * @param objectPath the D-Bus object path of the item
     * @param callback   a function that receives the decrypted secret and returns a result
     * @param <R>        the return type of the callback
     * @return the callback's result wrapped in Optional, or empty if the secret could not be retrieved
     */
    <R> Optional<R> withSecret(String objectPath, Function<char[], R> callback);

    /**
     * Retrieve all decrypted secrets in this collection.
     *
     * <p><b>Security note:</b> The caller is responsible for clearing each returned {@code char[]}
     * after use (e.g., {@code Arrays.fill(chars, '\0')}) to prevent sensitive material from
     * lingering in heap memory. Requires user permission to unlock the collection.</p>
     *
     * @return a map of item object paths to their decrypted secrets, or empty if unavailable
     */
    Optional<Map<String, char[]>> getSecrets();

    boolean isLocked();

    boolean lock();

    boolean unlockWithUserPermission();

    boolean updateItem(String objectPath, String label, CharSequence password, Map<String, String> attributes);

    boolean lockItem(String objectPath);

    boolean unlockItem(String objectPath);

    boolean disablePrompt();

    boolean enablePrompt();

}
