package de.swiesend.secretservice.functional.interfaces;

import de.swiesend.secretservice.functional.SearchMode;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.function.Function;

public interface CollectionInterface extends AutoCloseable {

    /**
     * Clear the collection password.
     *
     * @return true, if password could be cleared else false.
     */
    boolean clear();

    /**
     * Create an item in the collection.
     *
     * @param label  The label is a description. It is not a unique identifier.
     * @param secret The secret to be stored. One can encrypt the secret in beforehand,
     *               to avoid unwanted access from malicious applications.
     * @return item path, which is a unique reference generated by the provider
     */
    Optional<String> createItem(String label, CharSequence secret);

    /**
     * Create an item in the collection.
     *
     * @param label      The label is a description. It is not a unique identifier.
     * @param secret     The secret to be stored. One can encrypt the secret in beforehand,
     *                   to avoid unwanted access from malicious applications.
     * @param attributes Attributes are provided as a mapping of custom keys and values.
     *                   Applications often identify their secrets using the key `application`
     *                   and their application name as value and providing a unique identifier
     *                   for a specific secret in order to find it by its attributes instead
     *                   of the generated item path.
     *                   <p>
     *                   e.g.:
     *                   <code>
     *                   {
     *                   "application": "APPLICATION_NAME",
     *                   "uuid": "f773dd93-4869-4897-be9d-c53f5b43f904"
     *                   }
     *                   </code>
     * @return item path, which is a unique reference generated by the provider
     */
    Optional<String> createItem(String label, CharSequence secret, Map<String, String> attributes);

    boolean delete();

    boolean deleteItem(String objectPath);

    boolean deleteItems(List<String> objectPaths);

    Optional<Map<String, String>> getAttributes(String objectPath);

    /**
     * Object paths of the items matching every entry in {@code attributes}; an empty map returns
     * all items in the collection.
     *
     * <p><b>An empty result and a failed search are different things</b>, and callers that destroy
     * or overwrite data on the strength of this answer must distinguish them:</p>
     * <ul>
     *   <li>{@code Optional.of(List.of())} — the search <em>succeeded</em> and matched nothing.</li>
     *   <li>{@code Optional.empty()} — the search <em>failed</em> (the daemon did not answer, or
     *       {@code attributes} was null). Nothing may be inferred about the collection's contents.</li>
     * </ul>
     *
     * <p><b>Changed in 3.0.0.</b> Earlier releases collapsed both cases to {@code Optional.empty()},
     * so code of the form {@code if (getItems(a).isPresent()) …} previously implied "there are
     * matches" and no longer does — such a caller now enters that branch with an empty list. The
     * legacy {@code SimpleCollection.getItems} adapter deliberately keeps the old shape, returning
     * {@code null} for both.</p>
     */
    Optional<List<String>> getItems(Map<String, String> attributes);

    /**
     * Search all items using substring matching against the given mode.
     *
     * @param query case-insensitive substring to search for; empty string returns all items
     * @param mode  which field to match against
     * @return unmodifiable list of matching D-Bus object paths (never null)
     */
    List<String> search(String query, SearchMode mode);

    /**
     * Search all items using fuzzy (Levenshtein) matching against the given mode.
     * Falls back to substring matching when {@code maxDistance} is 0.
     *
     * @param query       case-insensitive query string
     * @param mode        which field to match against
     * @param maxDistance maximum edit distance to consider a match
     * @return unmodifiable list of matching D-Bus object paths (never null)
     */
    List<String> search(String query, SearchMode mode, int maxDistance);

    Optional<String> getItemLabel(String objectPath);

    boolean setItemLabel(String objectPath, String label);

    boolean setLabel(String label);

    Optional<String> getLabel();

    Optional<String> getId();

    /**
     * Retrieve a decrypted secret by its object path.
     *
     * <p><b>Security note:</b> The caller is responsible for clearing the returned {@code char[]}
     * after use (e.g., {@code Arrays.fill(chars, '\0')}) to prevent sensitive material from
     * lingering in heap memory. Prefer {@link #withSecret(String, Function)} which handles
     * cleanup automatically.</p>
     *
     * @param objectPath the D-Bus object path of the item
     * @return the decrypted secret as a char array, or empty if the item does not exist or is locked
     */
    Optional<char[]> getSecret(String objectPath);

    /**
     * Access a decrypted secret within a callback, guaranteeing the secret bytes are cleared
     * from memory after the callback returns (or throws).
     *
     * <p>This is the recommended way to access secrets. The library decrypts the secret,
     * passes the {@code char[]} to the callback, and zeroes the array in a {@code finally}
     * block -- the caller never needs to manage cleanup.</p>
     *
     * <p>Example usage:</p>
     * <pre>{@code
     * Optional<Boolean> authenticated = collection.withSecret(itemPath, secret -> {
     *     return checkPassword(secret);
     * });
     * }</pre>
     *
     * @param objectPath the D-Bus object path of the item
     * @param callback   a function that receives the decrypted secret and returns a non-null result.
     *                   If the callback returns {@code null}, the result is indistinguishable from
     *                   a missing secret (both yield {@code Optional.empty()}). Callbacks that need
     *                   to express "no value" should return a wrapper type (e.g., {@code Optional<T>})
     *                   or a sentinel value instead of {@code null}.
     * @param <R>        the return type of the callback
     * @return the callback's result wrapped in Optional, or empty if the secret could not be
     *         retrieved <b>or</b> the callback returned {@code null}
     */
    <R> Optional<R> withSecret(String objectPath, Function<char[], R> callback);

    /**
     * Retrieve all decrypted secrets in this collection.
     *
     * <p><b>Security note:</b> The caller is responsible for clearing each returned {@code char[]}
     * after use (e.g., {@code Arrays.fill(chars, '\0')}) to prevent sensitive material from
     * lingering in heap memory. Prefer {@link #withSecrets(Function)} which handles
     * cleanup automatically. Requires user permission to unlock the collection.</p>
     *
     * @return a map of item object paths to their decrypted secrets, or empty if unavailable
     */
    Optional<Map<String, char[]>> getSecrets();

    /**
     * Access all decrypted secrets within a callback, guaranteeing all secret bytes are cleared
     * from memory after the callback returns (or throws).
     *
     * <p>This is the recommended way to access multiple secrets. The library decrypts all
     * secrets, passes the map to the callback, and zeroes every {@code char[]} value in
     * a {@code finally} block. Requires user permission to unlock the collection.</p>
     *
     * <p>Example usage:</p>
     * <pre>{@code
     * Optional<List<String>> labels = collection.withSecrets(secrets -> {
     *     return secrets.entrySet().stream()
     *         .filter(e -> Arrays.equals(e.getValue(), "target".toCharArray()))
     *         .map(Map.Entry::getKey)
     *         .toList();
     * });
     * }</pre>
     *
     * @param callback a function that receives the map of object paths to decrypted secrets
     *                 and returns a non-null result. If the callback returns {@code null}, the
     *                 result is indistinguishable from a retrieval failure (both yield
     *                 {@code Optional.empty()}).
     * @param <R>      the return type of the callback
     * @return the callback's result wrapped in Optional, or empty if secrets could not be
     *         retrieved <b>or</b> the callback returned {@code null}
     */
    <R> Optional<R> withSecrets(Function<Map<String, char[]>, R> callback);

    boolean isLocked();

    boolean lock();

    boolean unlockWithUserPermission();

    boolean updateItem(String objectPath, String label, CharSequence password, Map<String, String> attributes);

    boolean lockItem(String objectPath);

    boolean unlockItem(String objectPath);

    boolean disablePrompt();

    boolean enablePrompt();

    /**
     * Detects the currently active Secret Service provider and returns its display name.
     *
     * @return display name such as {@code "KeePassXC"}, {@code "gnome-keyring"},
     *         {@code "unknown"}, or {@code "N/A"}
     * @see de.swiesend.secretservice.ProviderDetector#detect(org.freedesktop.dbus.connections.impl.DBusConnection)
     */
    String getProvider();

    /**
     * Detects the currently active Secret Service provider as a typed enum constant.
     *
     * @return the detected {@link de.swiesend.secretservice.ProviderDetector.Provider}
     */
    de.swiesend.secretservice.ProviderDetector.Provider detectProvider();

}
