name: ci

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version: [17, 20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install packages on linux
        run: >
          sudo apt-get -qq install -y --no-install-recommends dbus-x11 gnome-keyring dbus libdbus-glib-1-dev libsecret-tools
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
          cache: 'maven'
      - name: Maven Install
        run: |
          xvfb-run --auto-servernum bash <<EOF
            export $(dbus-launch)
            eval "$(echo '\n' | gnome-keyring-daemon --unlock)"
            mvn --batch-mode --update-snapshots -Dgpg.skip=true install
          EOF
